//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.MyDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emailDetail
    {
        public int id { get; set; }
        public string emailId { get; set; }
        public string pass { get; set; }
    }
}
